language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test:ci
  - yarn build
deploy:
  provider: npm
  email: malcolm.keeweesiong@gmail.com
  api_key:
    secure: Cm/OWu/HauUIuKxsfGY3X9KBbT/33NKfEajRtuSd1MHp/ZD3L1MaM+Z/jeoRHkR5ggS7UR0HcX8NLH0zefHO9k6aGDSdk/T27yVt0mgqDFSb4z8uOfntaU0jIdfQr0BLoihB9pWuN+MZFDx8ryuiCagqrol82YHfUuucxnMxhj1lkJKfpYVuiqEiFMi3EuY2jDvrmX09lfPqX/evmEuTqtL48yhpNHANMLFLeTH13Uohi8YEFru67j9uftb1Hmt80VZAKR/OXIMZIvfL+oQtOa4kPnUhKY/j4vsBnEkdSr3Ri50QErocSBkkvv/OIZu1xbmKsWFsOA/25g4ZWYpx9qLX0CarXDms6naYSOM40UB3RCyR6jOD83XiItAOdpQ+lfjpMbJONYf7vAH8OCbvwI2UbP9+oKB///ERHOLMAwy92wDOQ0xa6INFR0B/IJk8O3RxKFwEeJSxK0ccsjpQI0XFh9XrGuLuy0fodMYUKdkGXD4B/hYqwDbrgpWLWncDaMSwhRNIK4Jdux/p2yOyFn4esj+iJ1PCpeY1hM+nBTkY+4ZbDFL/9h5gpXg7zJfbFnM1gw9WwSpT5mw6reZ3C2kv/W7xvma844GjrYycXKwVM9/mt20F8GGFXgRlzIvx7Km+ppBOrvCVXjK/6xem8IhQrSvsar/1emiN2jotOtw=
  on:
    tags: true
    branch: master
  skip_cleanup: true
